cc_test(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/lib:bloom-filter",
        "//src/checker:spell-checker"
    ],
)