cc_library(
    name = "port-scanner-lib",
    srcs = ["port-scanner-lib.cc", "single-scan-lib.cc"],
    hdrs = ["port-scanner-lib.h", "single-scan-lib.h"],
    linkopts = ["-lpthread"],
    visibility = ["//visibility:public"]
)